repos:
  # core formatting and check hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - prevent large file commits
      - id: check-added-large-files
        args:
          # 30mb == 35,840kb
          - --maxkb=35840
      # - validate toml syntax
      - id: check-toml
      # - validate yaml syntax
      - id: check-yaml
        args:
          - --unsafe
      # - ensure files end with newline
      - id: end-of-file-fixer
      # - remove trailing whitespace
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2 # Ruff version
    hooks:
      - id: ruff-check # Run the linter
        args: [--fix]
      - id: ruff-format # Run the formatter
