repos:
  # core formatting and check hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - validate toml syntax
      - id: check-toml
      # - validate yaml syntax
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2 # Ruff version
    hooks:
      - id: ruff-check # Run the linter
        args: [--fix]
      - id: ruff-format # Run the formatter

  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
