# Exclude all snapshots from pre-commit hooks
exclude: '(^|/)snapshot(s)?/'
repos:
  # core formatting and check hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - validate toml syntax
      - id: check-toml
      # - validate yaml syntax
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7 # Ruff version
    hooks:
      - id: ruff-check # Run the linter
        args: [--fix]
      - id: ruff-format # Run the formatter

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
