FROM public.ecr.aws/lambda/python:3.12

LABEL org.opencontainers.image.source=https://github.com/CDCgov/dibbs-text-to-code
LABEL org.opencontainers.image.licenses=Apache-2.0

# Set the environment variable to prod by default
ARG ENVIRONMENT=prod
ENV ENVIRONMENT=${ENVIRONMENT}

# Initialize the text_to_code_lambda directory
RUN mkdir -p "${LAMBDA_TASK_ROOT}/src/text_to_code_lambda"

# Install build tools for compiling C++ extensions
RUN microdnf install -y gcc-c++ make && microdnf clean all

# Copy handler
COPY ./packages/text-to-code-lambda/src/text_to_code_lambda/lambda_function.py ${LAMBDA_TASK_ROOT}/src/text_to_code_lambda/lambda_function.py

# Copy over just the requirements-lambda.txt file and install the dependencies doing this
# before copying the rest of the code allows for caching of the dependencies
COPY ./packages/text-to-code-lambda/requirements-lambda.txt .
RUN pip install --no-cache-dir -r requirements-lambda.txt

# Copy over the rest of the code
COPY ./packages/text-to-code-lambda/src ${LAMBDA_TASK_ROOT}/src
COPY README.md ${LAMBDA_TASK_ROOT}/README.md

# Copy over model files and augmentation; shouldn't need index
COPY ./packages/text-to-code/src/services ${LAMBDA_TASK_ROOT}/src/services
COPY ./packages/text-to-code/src/models ${LAMBDA_TASK_ROOT}/src/models

ENV PYTHONPATH="${LAMBDA_TASK_ROOT}/src"

CMD [ "text_to_code_lambda.lambda_function.handler" ]