FROM public.ecr.aws/lambda/python:3.12

LABEL org.opencontainers.image.source=https://github.com/CDCgov/dibbs-text-to-code
LABEL org.opencontainers.image.licenses=Apache-2.0

# Set the environment variable to prod by default
ARG ENVIRONMENT=prod
ENV ENVIRONMENT=${ENVIRONMENT}

# Initialize the index_lambda directory
RUN mkdir -p "${LAMBDA_TASK_ROOT}/src/index_lambda"

# Install build tools for compiling C++ extensions
RUN microdnf install -y gcc-c++ make && microdnf clean all

# Copy over just the pyproject.toml file and install the dependencies doing this
# before copying the rest of the code allows for caching of the dependencies
COPY ./packages/utils ${LAMBDA_TASK_ROOT}/utils
RUN pip install --no-cache-dir "${LAMBDA_TASK_ROOT}/utils"

COPY ./packages/lambda-handler ${LAMBDA_TASK_ROOT}/lambda-handler
RUN pip install --no-cache-dir "${LAMBDA_TASK_ROOT}/lambda-handler"

COPY ./packages/index-lambda ${LAMBDA_TASK_ROOT}/index-lambda
RUN pip install --no-cache-dir "${LAMBDA_TASK_ROOT}/index-lambda"

# Copy over the rest of the code
COPY ./packages/index-lambda/src ${LAMBDA_TASK_ROOT}/src
COPY README.md ${LAMBDA_TASK_ROOT}/README.md

ENV PYTHONPATH="${LAMBDA_TASK_ROOT}/src/index_lambda"

CMD [ "index_lambda.lambda_function.handler" ]
