import re

ACADEMIC_CITATION_ACCESSED = re.compile(r"[Aa]ccessed \d{4}")
ACADEMIC_CITATION_FULL = re.compile(r"\d{4} [A-Za-z]{3}(\s\d+)?;\d+\(\d+\):\d+-\d+\.")
ACADEMIC_CITATION_PERIODICAL_LONG = re.compile(r"(\d{4})?,?[;\s]\d+:\d+\s?-\s?\d+(?!:)\.?")
ACADEMIC_CITATION_PERIODICAL_SHORT = re.compile(r"\d{4};\s\d*:\d*-\d*")
ACADEMIC_CITATION_SHORT = re.compile(r"\d{4};\s?\d*(\(\d+\))?:\d*-\d*")
BRACKETED_TEXT = re.compile(r"\[(?<=\[)[^\]]*?(?=\])\]")
DOUBLE_QUOTE_MARK = re.compile(r'""')
EC_REFERENCE = re.compile(r"\(?EC\s\d+\.\d+\.\d+\.\d+\)?")
LOINC_LINE_START = re.compile(r"^\d+-\d,")
MULTIPLE_SPACE = re.compile(r"\s+")
NCBI_REFERENCE = re.compile(r"NCBI\sBookself\s?,\s\d{4}")
PMID_REFERENCE = re.compile(r"PMID:\s\d+")
REF_ID_REFERENCE = re.compile(r"RefID\s\d{5}")
SPACED_PUNCTUATION_CLOSED_PAREN = re.compile(r"\s\)\s")
SPACED_PUNCTUATION_COMMA = re.compile(r"\s,\s")
SPACED_PUNCTUATION_OPEN_PAREN = re.compile(r"\s\(\s")
SPACED_PUNCTUATION_PERIOD = re.compile(r"\s\.\s")
TRAILING_QUOTE = re.compile(r'\s*"\s*$')
URL_EMBEDDED = re.compile(r"[\(\[\{]\s*[Hh]ttps?:(\/\/)?.+\s*[\)\]\}]")
URL_RAW = re.compile(r"(?<!\()[Hh]ttps?:\/\/.+")
