AUTO_MAPPING: dict[str, str] = {
    "# Baso": "Basophils # Bld Auto",
    "# Eos": "Eosinophil # Bld Auto",
    "# Lymphs": "Lymphocytes # Bld Auto",
    "# Monos": "Monocytes # Bld Auto",
    "# NEUT": "Neutrophils # Bld Auto",
    "# NRBC": "Nucleated erythrocytes/Leukocytes [Ratio] in Blood by Automated count",
    "# neut": "Neutrophils # Bld Auto",
    "#BA": "Basophils # Bld Auto",
    "#BASO": "Basophils # Bld Auto",
    "#BASO.": "Basophils # Bld Auto",
    "#EO": "Eosinophil # Bld Auto",
    "#EOS": "Eosinophil # Bld Auto",
    "#EOS.": "Eosinophil # Bld Auto",
    "#LYMPH": "Lymphocytes # Bld Auto",
    "#LYMPH.": "Lymphocytes # Bld Auto",
    "#MONO": "Monocytes # Bld Auto",
    "#MONO.": "Monocytes # Bld Auto",
    "#MONOS": "Monocytes # Bld Auto",
    "#NEUT": "Neutrophils # Bld Auto",
    "#NEUT.": "Neutrophils # Bld Auto",
    "#NRBC": "Nucleated erythrocytes/Leukocytes [Ratio] in Blood by Automated count",
    "#NRBCs": "Nucleated erythrocytes/Leukocytes [Ratio] in Blood by Automated count",
    "#ba": "Basophils # Bld Auto",
    "#baso": "Basophils # Bld Auto",
    "#eos": "Eosinophil # Bld Auto",
    "#lymph": "Lymphocytes # Bld Auto",
    "#mono": "Monocytes # Bld Auto",
    "#nRBC": "Nucleated erythrocytes/Leukocytes [Ratio] in Blood by Automated count",
    "#neut": "Neutrophils # Bld Auto",
    "% BASO": "Basophils NFr Bld Auto",
    "% Baso": "Basophils NFr Bld Auto",
    "% EOS": "Eosinophil NFr Bld Auto",
    "% Eos": "Eosinophil NFr Bld Auto",
    "% LYMPH": "Lymphocytes NFr Bld Auto",
    "% Lymphs": "Lymphocytes NFr Bld Auto",
    "% MONO": "Monocytes NFr Bld Auto",
    "% Monos": "Monocytes NFr Bld Auto",
    "% NRBC": "Nucleated erythrocytes/Leukocytes [Ratio] in Blood by Automated count",
    "% lymph": "Lymphocytes NFr Bld Auto",
    "% mono": "Monocytes NFr Bld Auto",
    "%BASO": "Basophils NFr Bld Auto",
    "%BASO.": "Basophils NFr Bld Auto",
    "%BASOS": "Basophils NFr Bld Auto",
    "%EO": "Eosinophil NFr Bld Auto",
    "%EOS": "Eosinophil NFr Bld Auto",
    "%EOS.": "Eosinophil NFr Bld Auto",
    "%LYMPH": "Lymphocytes NFr Bld Auto",
    "%LYMPH.": "Lymphocytes NFr Bld Auto",
    "%LYMPHS": "Lymphocytes NFr Bld Auto",
    "%MONO": "Monocytes NFr Bld Auto",
    "%MONO.": "Monocytes NFr Bld Auto",
    "%MONOS": "Monocytes NFr Bld Auto",
    "%NEUT": "Neutrophils NFr Bld Auto",
    "%NEUT.": "Neutrophils NFr Bld Auto",
    "%NRBC": "Nucleated erythrocytes/Leukocytes [Ratio] in Blood by Automated count",
    "%baso": "Basophils NFr Bld Auto",
    "%eos": "Eosinophil NFr Bld Auto",
    "%lymph": "Lymphocytes NFr Bld Auto",
    "%mono": "Monocytes NFr Bld Auto",
    "%neut": "Neutrophils NFr Bld Auto",
    "**CBC W/AUTO DIFF": "CBC W Auto Diff Bld",
    "**Comment**": "Service comment",
    "*A/G": "Albumin/Globulin [Mass ratio]",
    "*AGAP": "Anion gap in Serum or Plasma by calculation",
    "*ALB": "Albumin [Mass/volume] in Serum or Plasma",
    "*ALT": "ALT [Catalytic activity/Vol]",
    "*AST": "AST SerPl-cCnc",
    "*BUN": "BUN Bld-mCnc",
    "*CA": "Calcium [Mass/volume] in Serum or Plasma",
    "*CL": "Chloride SerPl-sCnc",
    "*CLARITY": "Clarity (U)",
    "*CO2": "CO2 [Moles/Vol]",
    "*Ca": "Calcium [Mass/volume] in Serum or Plasma",
    "*EGFRAA": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "*GLU": "Glucose [Mass/Vol]",
    "*HDL": "Cholesterol in HDL [Mass/volume] in Serum or Plasma",
    "*K": "Potassium [Moles/Vol]",
    "*NA": "Sodium [Moles/volume] in Serum or Plasma",
    "*Na": "Sodium [Moles/volume] in Serum or Plasma",
    "*PROTEIN": "Prot SerPl-mCnc",
    "*TP": "Protein [Mass/Vol]",
    "*TSH": "TSH Qn",
    "*agap": "Anion gap in Serum or Plasma by calculation",
    "*alb": "Albumin [Mass/volume] in Serum or Plasma",
    "*cL": "Chloride SerPl-sCnc",
    "*clarity": "Clarity (U)",
    "*co2": "CO2 [Moles/Vol]",
    "*creat": "Creat SerPl-mCnc",
    "*eGFR": "eGFRcr SerPlBld CKD-EPI 2021",
    "*egfraa": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "*glu": "Glucose [Mass/Vol]",
    "*protein": "Prot SerPl-mCnc",
    "*trig": "Trigl SerPl-mCnc",
    "+URINALYSIS": "Urinalysis complete panel - Urine",
    "=>BLOOD CULTURE<=": "Bacteria identified in Blood by Culture",
    "=>EKG<=": "12 lead EKG panel",
    "A GAP": "Anion gap in Serum or Plasma by calculation",
    "A/G": "Albumin/Globulin [Mass ratio]",
    "A/G RATIO": "Albumin/Globulin [Mass ratio]",
    "A/G RATIO.": "Albumin/Globulin [Mass ratio]",
    "A/G Ratio": "Albumin/Globulin [Mass ratio]",
    "A/G ratio": "Albumin/Globulin [Mass ratio]",
    "ABSOLUTE BASOPHIL": "Basophils [#/volume] in Blood by Automated count",
    "ABSOLUTE BASOPHILS": "Basophils [#/volume] in Blood by Automated count",
    "ABSOLUTE EOSINOPHIL": "Eosinophils [#/volume] in Blood",
    "ABSOLUTE EOSINOPHILS": "Eosinophils [#/volume] in Blood",
    "ABSOLUTE LYMPHOCYTE": "Lymphocytes [#/volume] in Blood by Automated count",
    "ABSOLUTE LYMPHOCYTES": "Lymphocytes [#/volume] in Blood by Automated count",
    "ABSOLUTE MONOCYTE": "Monocytes [#/volume] in Blood by Automated count",
    "ABSOLUTE MONOCYTES": "Monocytes [#/volume] in Blood by Automated count",
    "ABSOLUTE NEUTROPHIL": "Neutrophils [#/volume] in Blood by Automated count",
    "ABSOLUTE NEUTROPHILS": "Neutrophils [#/volume] in Blood by Automated count",
    "ADDITIONAL COMMENTS": "General comment",
    "AFR AMER GFR": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "AG": "Albumin/Globulin [Mass ratio]",
    "AG RATIO": "Albumin/Globulin [Mass ratio]",
    "AGAP": "Anion gap in Serum or Plasma by calculation",
    "AGE": "Age",
    "AGRATIO": "Albumin/Globulin [Mass ratio]",
    "ALB": "Albumin [Mass/volume] in Serum or Plasma",
    "ALBUMIN": "Albumin [Mass/Vol]",
    "ALBUMIN GLOBULIN RATIO": "Albumin/Globulin [Mass ratio]",
    "ALBUMIN.": "Albumin [Mass/Vol]",
    "ALK PHOS": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "ALKALINE PHOS": "ALP [Catalytic activity/Vol]",
    "ALKALINE PHOS.": "ALP [Catalytic activity/Vol]",
    "ALKALINE PHOSPHATASE": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "ALKPHOS": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "ALP": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "ALT": "ALT [Catalytic activity/Vol]",
    "ALT (SGPT)": "ALT SerPl-cCnc",
    "ALT / SGPT": "ALT SerPl-cCnc",
    "ALT SGPT": "ALT SerPl-cCnc",
    "ALT(SGPT)": "ALT SerPl-cCnc",
    "ALT(V)": "ALT [Catalytic activity/Vol]",
    "ALT-V": "ALT [Catalytic activity/Vol]",
    "ALT.": "ALT [Catalytic activity/Vol]",
    "ALT/SGPT": "ALT SerPl-cCnc",
    "ALTSGPT": "ALT SerPl-cCnc",
    "ALTV": "ALT [Catalytic activity/Vol]",
    "AMPHETAMINE": "Amphetamine Screen Ql (U)",
    "AMPHETAMINES": "Amphetamines Ur Ql",
    "ANISO": "Anisocytosis Bld Ql Smear",
    "APPEARANCE": "Appearance (U)",
    "APTT": "aPTT in Platelet poor plasma by Coagulation assay",
    "AST": "AST SerPl-cCnc",
    "AST (SGOT)": "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "AST / SGOT": "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "AST SGOT": "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "AST(SGOT)": "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "AST.": "AST SerPl-cCnc",
    "AST/SGOT": "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "ATRIAL RATE": "P wave Atrium by EKG",
    "ATYP LYMPH": "Variant Lymphs Bld Ql Auto",
    "ATYP LYMPHS": "Variant Lymphs Bld Ql Auto",
    "ATYPLYMPHS": "Variant Lymphs Bld Ql Auto",
    "Absolute Basophil": "Basophils [#/volume] in Blood by Automated count",
    "Absolute Basophils": "Basophils [#/volume] in Blood by Automated count",
    "Absolute Eosinophils": "Eosinophils [#/volume] in Blood",
    "Absolute Immature Granulocyte": "Immature granulocytes [#/volume] in Blood",
    "Absolute Immature Granulocytes": "Immature granulocytes [#/volume] in Blood",
    "Absolute Lymphocytes": "Lymphocytes [#/volume] in Blood by Automated count",
    "Absolute Monocyte": "Monocytes [#/volume] in Blood by Automated count",
    "Absolute Monocytes": "Monocytes [#/volume] in Blood by Automated count",
    "Absolute Neutrophil": "Neutrophils [#/volume] in Blood by Automated count",
    "Absolute Neutrophils": "Neutrophils [#/volume] in Blood by Automated count",
    "Additional Comment": "General comment",
    "Ag": "Albumin/Globulin [Mass ratio]",
    "Ag ratio": "Albumin/Globulin [Mass ratio]",
    "Albumin": "Albumin [Mass/Vol]",
    "Albumin / Globulin Ratio": "Albumin/Globulin [Mass ratio]",
    "Albumin, Serum": "Albumin [Mass/volume] in Serum or Plasma",
    "Albumin, serum": "Albumin [Mass/volume] in Serum or Plasma",
    "Albumin/Globulin Ratio": "Albumin/Globulin [Mass ratio]",
    "Alk Phos": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "Alkaline Phos": "ALP [Catalytic activity/Vol]",
    "Alkaline Phosphatase": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "Alkaline phosphatase": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "Alkaline phosphatase measurement": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "Amphetamine": "Amphetamine Screen Ql (U)",
    "Amphetamines": "Amphetamines Ur Ql",
    "Aniso": "Anisocytosis Bld Ql Smear",
    "Appearance": "Appearance (U)",
    "Assessment of urine color": "Color of Urine",
    "Atrial Rate": "P wave Atrium by EKG",
    "Atrial rate": "P wave Atrium by EKG",
    "Atyp lymphs": "Variant Lymphs Bld Ql Auto",
    "BA#": "Basophils # Bld Auto",
    "BACTERIA": "Bacteria Bld Cult",
    "BAND": "Neuts Band NFr Bld Manual",
    "BAND*": "Neuts Band NFr Bld Manual",
    "BANDS": "Neuts Band NFr Bld Manual",
    "BASO": "Basophils # Bld Auto",
    "BASO #": "Basophils # Bld Auto",
    "BASO %": "Basophils NFr Bld Auto",
    "BASO#": "Basophils # Bld Auto",
    "BASO%": "Basophils NFr Bld Auto",
    "BASO%.": "Basophils NFr Bld Auto",
    "BASO*": "Basophils # Bld Auto",
    "BASOPHIL": "Basophils [#/volume] in Blood by Automated count",
    "BASOPHILS": "Basophils [#/volume] in Blood by Automated count",
    "BASOS": "Basophils # Bld Auto",
    "BENZO": "Benzodiaz Ur Ql",
    "BENZODIAZEPINE": "Benzodiazepines Ql (U)",
    "BENZODIAZEPINES": "Benzodiazepines Ql (U)",
    "BENZODIAZEPINES SCRN": "Benzodiazepines [Presence] in Urine by Screen method",
    "BENZOS": "Benzodiaz Ur Ql",
    "BILIRUBIN": "Bilirub SerPl-mCnc",
    "BILIRUBIN TOTAL": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "BILIRUBIN, TOTAL": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "BLAST": "Blasts (Bld) [#/Vol]",
    "BLASTS": "Blasts (Bld) [#/Vol]",
    "BLOOD CULTURE": "Bacteria identified in Blood by Culture",
    "BLOOD EXPIRATION DATE": "Specimen expiration date of Blood",
    "BNP": "BNP SerPl-mCnc",
    "BUN": "BUN Bld-mCnc",
    "BUN creatinine ratio": "Urea nitrogen/Creatinine [Mass Ratio] in Blood",
    "BUN-crea": "Urea nitrogen/Creatinine [Mass Ratio] in Serum or Plasma",
    "BUN.": "BUN Bld-mCnc",
    "BUN/CREA": "Urea nitrogen/Creatinine [Mass Ratio] in Serum or Plasma",
    "BUN/CREAT": "BUN/Creat Bld",
    "BUN/CREATININE RATIO": "Urea nitrogen/Creatinine [Mass Ratio] in Blood",
    "BUN/Creatinine Ratio": "Urea nitrogen/Creatinine [Mass Ratio] in Blood",
    "BUN/crea": "Urea nitrogen/Creatinine [Mass Ratio] in Serum or Plasma",
    "BUN/creat": "BUN/Creat Bld",
    "BUN/creatinine ratio": "Urea nitrogen/Creatinine [Mass Ratio] in Blood",
    "BUNa": "Urea nitrogen [Mass/volume] in Serum or Plasma",
    "BUPRENORPHIHNES": "Buprenorphine Ur Ql",
    "BUPRENORPHINE": "Buprenorphine Ur Ql",
    "Bacteria": "Bacteria Bld Cult",
    "Band": "Neuts Band NFr Bld Manual",
    "Bands": "Neuts Band NFr Bld Manual",
    "Baso %": "Basophils NFr Bld Auto",
    "Basophil": "Basophils [#/volume] in Blood by Automated count",
    "Basophils": "Basophils [#/volume] in Blood by Automated count",
    "Basos": "Basophils # Bld Auto",
    "Benzodiazepine": "Benzodiazepines Ql (U)",
    "Benzodiazepine screen": "Benzodiazepines [Presence] in Urine by Screen method",
    "Benzos": "Benzodiaz Ur Ql",
    "Bilirubin": "Bilirub SerPl-mCnc",
    "Bilirubin (total)": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "Bilirubin Total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "Bilirubin total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "Bilirubin, Total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "Bilirubin, total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "Bilirubin,Total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "Blast": "Blasts (Bld) [#/Vol]",
    "Blasts": "Blasts (Bld) [#/Vol]",
    "Blood Culture": "Bacteria identified in Blood by Culture",
    "Blood Expiration Date": "Specimen expiration date of Blood",
    "Blood Urea Nitrogen": "Urea nitrogen [Mass/volume] in Blood",
    "Blood culture": "Bacteria identified in Blood by Culture",
    "Blood culture and sensitivity": "Bacteria identified in Blood by Culture",
    "Blood urea nitrogen (BUN) measurement": "Urea nitrogen [Mass/volume] in Blood",
    "Bun": "BUN Bld-mCnc",
    "Buprenorphine": "Buprenorphine Ur Ql",
    "CA": "Calcium [Mass/volume] in Serum or Plasma",
    "CALCIUM": "Calcium [Mass/Vol]",
    "CALCIUM.": "Calcium [Mass/Vol]",
    "CARDIAC PANEL": "12 lead EKG Pnl",
    "CBC": "CBC Pnl Bld Auto",
    "CBC (+)": "CBC Pnl Bld Auto",
    "CBC (w/ auto diff)": "CBC W Auto Diff Bld",
    "CBC W/ AUTO DIFF": "CBC W Auto Diff Bld",
    "CBC W/AUTO DIFF": "CBC W Auto Diff Bld",
    "CBC WITH DIFF": "CBC W Auto Diff Bld",
    "CHLORIDE": "Chloride [Moles/Vol]",
    "CHLORIDE.": "Chloride [Moles/Vol]",
    "CHOL/HDL RATIO": "Cholesterol.total/Cholesterol in HDL [Mass Ratio] in Serum or Plasma",
    "CHOLESTEROL": "Cholesterol [Mass/Vol]",
    "CL": "Chloride SerPl-sCnc",
    "CL-": "Chloride SerPl-sCnc",
    "CLARITY": "Clarity (U)",
    "CO2": "CO2 [Moles/Vol]",
    "CO2 Whole Blood": "Carbon dioxide, total [Moles/volume] in Blood",
    "CO2.": "CO2 [Moles/Vol]",
    "COCAINE": "Benzoylecgonine Ql (U)",
    "COCAINE METABOLITE": "Benzoylecgonine [Presence] in Urine",
    "COLOR": "Color (U)",
    "COLOR.": "Color (U)",
    "COLOR..": "Color (U)",
    "COMMENT": "Service comment",
    "COMMENT(S)": "Service comment",
    "COMMENTS": "Service comment",
    "CORRECTED CALCIUM": "Calcium corrected for albumin [Mass/Vol]",
    "CPK": "Creatine kinase [Enzymatic activity/volume] in Serum or Plasma",
    "CREAT": "Creat SerPl-mCnc",
    "CREATININE": "Creatinine [Mass/Vol]",
    "CREATININE-S": "Creatinine [Mass/Vol]",
    "CREATININE.": "Creatinine [Mass/Vol]",
    "CRP": "C reactive protein [Mass/volume] in Serum or Plasma",
    "CRP*": "C reactive protein [Mass/volume] in Serum or Plasma",
    "CULTURE - URINE": "Bacteria identified in Urine by Culture",
    "CULTURE URINE": "Bacteria identified in Urine by Culture",
    "Ca": "Calcium [Mass/volume] in Serum or Plasma",
    "Ca++": "Calcium [Mass/volume] in Serum or Plasma",
    "Calcium": "Calcium [Mass/Vol]",
    "Calcium measurement": "Calcium [Mass/volume] in Serum or Plasma",
    "Cap Glucose": "Glucose [Mass/volume] in Capillary blood",
    "Capillary-glucose": "Glucose [Mass/volume] in Capillary blood",
    "Cardiac Panel": "12 lead EKG Pnl",
    "Chloride": "Chloride [Moles/Vol]",
    "Chloride Whole Blood": "Chloride [Moles/volume] in Blood",
    "Chloride, Whole Blood": "Chloride [Moles/volume] in Blood",
    "Chol/HDL Ratio": "Cholesterol.total/Cholesterol in HDL [Mass Ratio] in Serum or Plasma",
    "Cholesterol": "Cholesterol [Mass/Vol]",
    "Cl-": "Chloride SerPl-sCnc",
    "Clarity": "Clarity (U)",
    "Cocaine": "Benzoylecgonine Ql (U)",
    "Color": "Color (U)",
    "Comment": "Service comment",
    "Comments": "Service comment",
    "Corrected Calcium": "Calcium corrected for albumin [Mass/Vol]",
    "Creatinine": "Creatinine [Mass/Vol]",
    "Culture Urine": "Bacteria identified in Urine by Culture",
    "Culture, Urine": "Bacteria identified in Urine by Culture",
    "Culture, urine": "Bacteria identified in Urine by Culture",
    "Diagnosis": "Dx",
    "ECG Interp": "EKG impression",
    "EGFR": "eGFRcr SerPlBld CKD-EPI 2021",
    "EGFR AA": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "EGFRAA": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "EKG": "12 lead EKG panel",
    "EO": "Eosinophils [#/volume] in Blood by Automated count",
    "EO %": "Eosinophil NFr Bld Auto",
    "EO#": "Eosinophil # Bld Auto",
    "EO%": "Eosinophil NFr Bld Auto",
    "EOS": "Eosinophils [#/volume] in Blood by Automated count",
    "EOS %": "Eosinophil NFr Bld Auto",
    "EOS%": "Eosinophil NFr Bld Auto",
    "EOS*": "Eosinophils [#/volume] in Blood by Automated count",
    "EOSINOPHIL": "Eosinophils [#/volume] in Blood by Automated count",
    "EOSINOPHILS": "Eosinophils [#/volume] in Blood by Automated count",
    "EPITHELIAL": "Epithelial cells [Presence] in Urine sediment by Light microscopy",
    "EPITHELIALS": "Epithelial cells [Presence] in Urine sediment by Light microscopy",
    "Eos": "Eosinophils [#/volume] in Blood by Automated count",
    "Eosinophil": "Eosinophils [#/volume] in Blood by Automated count",
    "Eosinophils": "Eosinophils [#/volume] in Blood by Automated count",
    "Epithelial": "Epithelial cells [Presence] in Urine sediment by Light microscopy",
    "Epithelials": "Epithelial cells [Presence] in Urine sediment by Light microscopy",
    "Estimated average blood glucose determination based on hemoglobin A1c": "Glucose mean value [Mass/volume] in Blood Estimated from glycated hemoglobin",
    "FASTING": "Fasting status - Reported",
    "FASTING?": "Fasting status - Reported",
    "FENTANYL": "fentaNYL Ur Ql",
    "FENTANYL, URINE": "fentaNYL [Presence] in Urine",
    "FERRITIN": "Ferritin [Mass/volume] in Serum or Plasma",
    "FI O2": "FIO2",
    "FIO2": "FIO2",
    "Fasting": "Fasting status - Reported",
    "Fasting?": "Fasting status - Reported",
    "Fentanyl": "fentaNYL Ur Ql",
    "Fentanyl Screen, Urine": "fentaNYL [Presence] in Urine by Screen method",
    "Ferritin": "Ferritin [Mass/volume] in Serum or Plasma",
    "FiO2": "FIO2",
    "Folate": "Folate [Mass/Vol]",
    "Folate, Serum": "Folate [Mass/volume] in Serum or Plasma",
    "Folic Acid": "Folate [Mass/volume] in Serum or Plasma",
    "GFR": "eGFRcr SerPlBld CKD-EPI 2021",
    "GFR+": "eGFRcr SerPlBld CKD-EPI 2021",
    "GFR-": "eGFRcr SerPlBld CKD-EPI 2021",
    "GFR.": "eGFRcr SerPlBld CKD-EPI 2021",
    "GFRa": "Glomerular filtration rate [Volume Rate/Area] in Serum or Plasma by Creatinine-based formula (MDRD)/1.73 sq M",
    "GFRaAA": "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (MDRD)/1.73 sq M among black population",
    "GLOBULIN": "Globulin Calc (S) [Mass/Vol]",
    "GLOBULIN.": "Globulin Calc (S) [Mass/Vol]",
    "GLU": "Glucose [Mass/Vol]",
    "GLUCOMETER": "Glucose Glucometer (BldC) [Mass/Vol]",
    "GLUCOSE": "Glucose [Mass/Vol]",
    "GLUCOSE BEDSIDE": "Glucose BldC Glucomtr-mCnc",
    "GLUCOSE POC": "Glucose (Bld) [Mass/Vol]",
    "GLUCOSE, BEDSIDE": "Glucose BldC Glucomtr-mCnc",
    "GLUCOSE, POC": "Glucose (Bld) [Mass/Vol]",
    "GLUCOSE.": "Glucose [Mass/Vol]",
    "GLUCOSEa": "Glucose [Mass/volume] in Serum or Plasma",
    "Gastric NGT": "Type of Nasogastric tube",
    "Globulin": "Globulin Calc (S) [Mass/Vol]",
    "Glu": "Glucose [Mass/Vol]",
    "Glucose": "Glucose [Mass/Vol]",
    "Glucose (POC)": "Glucose (Bld) [Mass/Vol]",
    "Glucose POC": "Glucose (Bld) [Mass/Vol]",
    "Glucose, Bedside": "Glucose BldC Glucomtr-mCnc",
    "Glucose, POC": "Glucose (Bld) [Mass/Vol]",
    "Glucose, Whole Blood": "Glucose [Mass/Volume] in Blood",
    "Glucose,POC": "Glucose (Bld) [Mass/Vol]",
    "Glucose,Poc": "Glucose (Bld) [Mass/Vol]",
    "Glucose-Capillary": "Glucose [Mass/volume] in Capillary blood",
    "Grans, Immature": "Immature granulocytes [#/volume] in Blood",
    "Granulocytes, Immature": "Immature granulocytes [#/volume] in Blood",
    "Granulocytes, Immature (Absolute)": "Immature granulocytes [#/volume] in Blood",
    "HCT": "Hct VFr Bld Auto",
    "HCT, Whole Blood": "Hct VFr Bld Imped",
    "HCT.": "Hct VFr Bld Auto",
    "HDL": "Cholesterol in HDL [Mass/volume] in Serum or Plasma",
    "HDL CHOLESTEROL": "Cholesterol in HDL [Mass/Vol]",
    "HDL cholesterol": "Cholesterol in HDL [Mass/Vol]",
    "HDL-cholesterol": "Cholesterol in HDL [Mass/Vol]",
    "HDL.": "Cholesterol in HDL [Mass/volume] in Serum or Plasma",
    "HEMATOCRIT": "Hematocrit Auto (Bld) [Volume fraction]",
    "HEMATOCRIT.": "Hematocrit Auto (Bld) [Volume fraction]",
    "HEMOGLOBIN": "Hemoglobin [Mass/volume] in Blood",
    "HEMOGLOBIN.": "Hemoglobin [Mass/volume] in Blood",
    "HEPATITIS B SURFACE ANTIGEN": "Hepatitis B virus surface Ag [Presence] in Serum or Plasma by Immunoassay",
    "HEPATITIS B SURFACEANTIGEN": "Hepatitis B virus surface Ag [Presence] in Serum or Plasma by Immunoassay",
    "HEPATITIS C ANTIBODY": "Hepatitis C virus Ab [Presence] in Serum",
    "HGB": "Hgb Bld-mCnc",
    "HGB S": "Hgb S Bld Ql Soly",
    "HGB-S": "Hgb S Bld Ql Soly",
    "HGB.": "Hgb Bld-mCnc",
    "HYALINE CAST": "Hyaline casts [#/area] in Urine sediment by Microscopy low power field",
    "Hct": "Hct VFr Bld Auto",
    "Hematocrit": "Hematocrit Auto (Bld) [Volume fraction]",
    "Hematocrit, Whole Blood": "Hematocrit [Volume Fraction] of Blood by Impedance",
    "Hemoglobin": "Hemoglobin [Mass/volume] in Blood",
    "Hep B Surf Ag (REFL)": "HBV surface Ag Confirm Ql",
    "Hep B Surface Ag reflex": "HBV surface Ag Confirm Ql",
    "Hep B Surface Antigen (Reflex)": "HBV surface Ag Confirm Ql",
    "Hepatitis B Surface Antigen": "Hepatitis B virus surface Ag [Presence] in Serum or Plasma by Immunoassay",
    "Hepatitis C Antibody": "Hepatitis C virus Ab [Presence] in Serum",
    "Hepatitis, B Surface Antigen": "Hepatitis B virus surface Ag [Presence] in Serum or Plasma by Immunoassay",
    "Hepatitis, C Antibody": "Hepatitis C virus Ab [Presence] in Serum",
    "Hyaline Casts": "Hyaline casts [#/area] in Urine sediment by Microscopy low power field",
    "Hydrocodone, Urine": "HYDROcodone [Mass/volume] in Urine",
    "Hydromorphone (Urine)": "HYDROmorphone [Mass/volume] in Urine",
    "IMMATURE GRANULOCYTE": "Immature granulocytes [Presence] in Blood by Automated count",
    "IMMATURE GRANULOCYTES": "Immature granulocytes [Presence] in Blood by Automated count",
    "INR": "INR in Platelet poor plasma by Coagulation assay",
    "IRON": "Iron [Mass/volume] in Serum or Plasma",
    "IRON.": "Iron [Mass/volume] in Serum or Plasma",
    "Immature Grans (Abs)": "Immature granulocytes [#/volume] in Blood",
    "Immature Grans (Absolute)": "Immature granulocytes [#/volume] in Blood",
    "Immature Granulocyte": "Immature granulocytes [Presence] in Blood by Automated count",
    "Immature Granulocytes": "Immature granulocytes [Presence] in Blood by Automated count",
    "Iron": "Iron [Mass/volume] in Serum or Plasma",
    "K": "Potassium [Moles/Vol]",
    "K+": "Potassium [Moles/Vol]",
    "Ketones Urine POC": "Ketones Test strip Ql (U)",
    "Ketones in Urine": "Ketones [Mass/volume] in Urine",
    "LACTIC ACID": "Lactate [Moles/Vol]",
    "LACTIC ACID S": "Lactate [Moles/Vol]",
    "LDL / HDL": "LDLc/HDLc SerPl",
    "LDL/HDL": "LDLc/HDLc SerPl",
    "LEUK EST": "Leukocytes [#/volume] in Blood by Estimate",
    "LEUKOCYTE": "Leukocytes [#/volume] in Blood by Automated count",
    "LEUKOCYTE ESTERASE": "Leukocyte esterase [Presence] in Urine by Test strip",
    "LEUKOCYTES": "Leukocytes [#/volume] in Blood by Automated count",
    "LIPASE": "Lipase [Catalytic activity/Vol]",
    "LY %": "Lymphocytes NFr Bld Auto",
    "LY%": "Lymphocytes NFr Bld Auto",
    "LYMPH": "Lymphocytes [#/volume] in Blood by Automated count",
    "LYMPH #": "Lymphocytes # Bld Auto",
    "LYMPH %": "Lymphocytes NFr Bld Auto",
    "LYMPH#": "Lymphocytes # Bld Auto",
    "LYMPH%": "Lymphocytes NFr Bld Auto",
    "LYMPH*": "Lymphocytes [#/volume] in Blood by Automated count",
    "LYMPHOCYTES": "Lymphocytes [#/volume] in Blood by Automated count",
    "LYMPHS": "Lymphocytes [#/volume] in Blood by Automated count",
    "Lactic Acid": "Lactate [Moles/Vol]",
    "Leuk Est": "Leukocytes [#/volume] in Blood by Estimate",
    "Leukocyte": "Leukocytes [#/volume] in Blood by Automated count",
    "Leukocyte Esterase": "Leukocyte esterase [Presence] in Urine by Test strip",
    "Leukocyte esterase": "Leukocyte esterase [Presence] in Urine by Test strip",
    "Leukocytes": "Leukocytes [#/volume] in Blood by Automated count",
    "Leukocytes.": "Leukocytes [#/volume] in Blood by Automated count",
    "Lipase": "Lipase [Catalytic activity/Vol]",
    "Lymph": "Lymphocytes [#/volume] in Blood by Automated count",
    "Lymph %": "Lymphocytes NFr Bld Auto",
    "Lymphocyte %": "Lymphocytes/Leukocytes in Blood by Automated count",
    "Lymphocyte (%)": "Lymphocytes/Leukocytes in Blood by Automated count",
    "Lymphocytes %": "Lymphocytes/Leukocytes in Blood by Automated count",
    "Lymphocytes (%)": "Lymphocytes/Leukocytes in Blood by Automated count",
    "Lymphs": "Lymphocytes [#/volume] in Blood by Automated count",
    "MAGNESIUM": "Magnesium [Moles/Vol]",
    "MANUAL DIFF": "Manual differential performed Bld Ql",
    "MANUAL DIFF.?": "Manual differential performed Bld Ql",
    "MANUAL DIFF?": "Manual differential performed Bld Ql",
    "MCH": "MCH RBC Qn Auto",
    "MCH.": "MCH RBC Qn Auto",
    "MCHC": "MCHC Auto (RBC) [Entitic Mass/Vol]",
    "MCHC.": "MCHC Auto (RBC) [Entitic Mass/Vol]",
    "MCV": "MCV RBC Auto",
    "MCV.": "MCV RBC Auto",
    "MDW": "MDW Bld Auto",
    "METAMYELOCYTE": "Metamyelocytes # Bld",
    "METAMYELOCYTES": "Metamyelocytes # Bld",
    "METHADONE": "Methadone [Mass/volume] in Urine",
    "METHADoNE": "Methadone [Mass/volume] in Urine",
    "MO#": "Monocytes # Bld Auto",
    "MO#.": "Monocytes # Bld Auto",
    "MO%": "Monocytes NFr Bld Auto",
    "MO%.": "Monocytes NFr Bld Auto",
    "MONO": "Monocytes [#/volume] in Blood by Automated count",
    "MONO #": "Monocytes [#/volume] in Blood by Automated count",
    "MONO %": "Monocytes NFr Bld Auto",
    "MONO#": "Monocytes [#/volume] in Blood by Automated count",
    "MONO#.": "Monocytes [#/volume] in Blood by Automated count",
    "MONO%": "Monocytes NFr Bld Auto",
    "MONO%.": "Monocytes NFr Bld Auto",
    "MONO*": "Monocytes [#/volume] in Blood by Automated count",
    "MONOCYTE": "Monocytes [#/volume] in Blood by Automated count",
    "MONOCYTES": "Monocytes [#/volume] in Blood by Automated count",
    "MONOCYTES%": "Monocytes/Leukocytes in Blood by Automated count",
    "MONOS": "Monocytes [#/volume] in Blood by Automated count",
    "MPV.": "PMV Bld Auto",
    "MUCOUS": "Mucous Threads UrnS Ql Micro ",
    "MUCUS": "Mucus [Presence] in Urine sediment by Light microscopy",
    "MVP": "PMV Bld Auto",
    "MYELOCYTE": "Myelocytes # Bld Manual",
    "MYELOCYTES": "Myelocytes # Bld Manual",
    "Magnesium": "Magnesium [Moles/Vol]",
    "Magnesium measurement": "Magnesium [Mass/Vol]",
    "Manual Diff": "Manual differential performed Bld Ql",
    "Mch": "MCH RBC Qn Auto",
    "Mchc": "MCHC Auto (RBC) [Entitic Mass/Vol]",
    "Mcv": "MCV RBC Auto",
    "Mean Corpuscular HGB Conc": "MCHC [Entitic Mass/volume] in Red Blood Cells by Automated count",
    "Mean Corpuscular Volume": "MCV [Entitic mean volume] in Red Blood Cells by Automated count",
    "Mean CorpuscularHemoglobin": "MCH [Entitic mass] by Automated count",
    "Mean Platelet Volume": "Platelet [Entitic mean volume] in Blood by Automated count",
    "Mean corpuscular hemoglobin (MCH) determination": "MCH [Entitic mass] by Automated count",
    "Mean corpuscular hemoglobin concentration (MCHC) determination": "MCHC [Entitic Mass/volume] in Red Blood Cells by Automated count",
    "Mean platelet volume": "Platelet [Entitic mean volume] in Blood by Automated count",
    "Metamyelocyte": "Metamyelocytes # Bld",
    "Metamyelocytes": "Metamyelocytes # Bld",
    "Methadone": "Methadone [Mass/volume] in Urine",
    "Methadone Screen": "Methadone Screen Ql (U)",
    "Methadone Screen, Urine": "Methadone Screen Ql (U)",
    "Methadone Urine": "Methadone [Mass/volume] in Urine",
    "Methadone, Qual (U)": "Methadone Screen Ql (U)",
    "Methadone, Urine": "Methadone [Mass/volume] in Urine",
    "Mono #": "Monocytes [#/volume] in Blood by Automated count",
    "Mono %": "Monocytes NFr Bld Auto",
    "Monocyte": "Monocytes [#/volume] in Blood by Automated count",
    "Monocyte (%)": "Monocytes/Leukocytes in Blood by Automated count",
    "Monocytes": "Monocytes [#/volume] in Blood by Automated count",
    "Monocytes %": "Monocytes/Leukocytes in Blood by Automated count",
    "MpV": "PMV Bld Auto",
    "Mpv": "PMV Bld Auto",
    "Mucous": "Mucous Threads UrnS Ql Micro ",
    "Mucus": "Mucus [Presence] in Urine sediment by Light microscopy",
    "Myelocyte": "Myelocytes # Bld Manual",
    "Myelocytes": "Myelocytes # Bld Manual",
    "N RBC": "nRBC # Bld Auto",
    "NA": "Sodium [Moles/volume] in Serum or Plasma",
    "NA+": "Sodium [Moles/volume] in Serum or Plasma",
    "NAS": "Sodium [Moles/volume] in Serum or Plasma",
    "NEUT #": "Neutrophils # Bld Auto",
    "NEUT %": "Neutrophils/Leukocytes in Blood by Automated count",
    "NEUT#": "Neutrophils # Bld Auto",
    "NEUT%": "Neutrophils/Leukocytes in Blood by Automated count",
    "NEUTROPHIL": "Neutrophils [#/volume] in Blood by Automated count",
    "NEUTROPHILS": "Neutrophils [#/volume] in Blood by Automated count",
    "NITRITE": "Nitrite Ur Ql Strip",
    "NITRITES": "Nitrite Ur Ql Strip",
    "NON AA GFR": "GFR Creatinine-based formula (MDRD)/1.73 sq M among non black population (S/P/Bld) [Vol rate/Area]",
    "NON-AA GFR": "GFR Creatinine-based formula (MDRD)/1.73 sq M among non black population (S/P/Bld) [Vol rate/Area]",
    "NOTES": "Note",
    "NRBC": "nRBC # Bld Auto",
    "NRBC #": "nRBC # Bld Auto",
    "NRBC %": "nRBC Bld Auto-Rto",
    "NRBC#": "nRBC # Bld Auto",
    "NRBC%": "nRBC Bld Auto-Rto",
    "NRBC's": "nRBC # Bld Auto",
    "NRBCs": "nRBC # Bld Auto",
    "Na": "Sodium [Moles/volume] in Serum or Plasma",
    "Na+": "Sodium [Moles/volume] in Serum or Plasma",
    "Neut #": "Neutrophils # Bld Auto",
    "Neut %": "Neutrophils/Leukocytes in Blood by Automated count",
    "Neutrophil": "Neutrophils [#/volume] in Blood by Automated count",
    "Neutrophils": "Neutrophils [#/volume] in Blood by Automated count",
    "Nitrite": "Nitrite Ur Ql Strip",
    "Nitrite.": "Nitrite Ur Ql Strip",
    "Nitrites": "Nitrite Ur Ql Strip",
    "Note": "Note",
    "Notes": "Note",
    "OPIATE": "Opiates Ur Ql",
    "OPIATES": "Opiates Ur Ql",
    "OSMOLALITY": "Osmolality [Osmolality]",
    "OSMOLALITY.": "Osmolality [Osmolality]",
    "OXYCODONE": "oxyCODONE Screen Ql (U)",
    "Opiates": "Opiates Ur Ql",
    "Osmolality": "Osmolality [Osmolality]",
    "Oxycodone": "oxyCODONE Screen Ql (U)",
    "P AXIS": "P wave axis",
    "P Axis": "P wave axis",
    "P axis": "P wave axis",
    "P-Axis": "P wave axis",
    "P-R INTERVAL": "P-R Interval",
    "PCP": "PCP Ur Ql",
    "PERFORMING LAB": "Performing lab name",
    "PHOSPHORUS SERUM": "Phosphate [Mass/volume] in Serum or Plasma",
    "PLATELET": "Platelets [#/volume] in Blood by Automated count",
    "PLATELET COUNT": "Platelets [#/volume] in Blood by Automated count",
    "PLATELETS": "Platelets [#/volume] in Blood by Automated count",
    "PLATELETS*": "Platelets [#/volume] in Blood by Automated count",
    "PLATELETS.": "Platelets [#/volume] in Blood by Automated count",
    "PLT": "Platelet # Bld Auto",
    "PLT EST": "Platelets [#/volume] in Blood by Estimate",
    "PLT Est": "Platelets [#/volume] in Blood by Estimate",
    "PLT MORPH": "Platelets [Morphology] in Blood",
    "PLTEST": "Platelets [#/volume] in Blood by Estimate",
    "PLTS": "Platelet # Bld Auto",
    "PLt": "Platelet # Bld Auto",
    "POC CHLORIDE": "Chloride [Moles/volume] in Blood",
    "POC CO2": "CO2 (Bld) [Moles/Vol]",
    "POC CREATININE": "Creatinine [Mass/volume] in Blood",
    "POC Chloride": "Chloride [Moles/volume] in Blood",
    "POC Creatinine": "Creatinine [Mass/volume] in Blood",
    "POC GLUCOSE": "Glucose [Mass/Volume] in Blood",
    "POC Gastric pH": "pH total acid of Gastric fluid",
    "POC Gluc Interpretative Data": "Glucose tolerance [Interpretation] in Serum or Plasma",
    "POC Glucose": "Glucose [Mass/Volume] in Blood",
    "POC HCG": "HCG Ur Ql",
    "POC HCT": "Hct VFr Bld Imped",
    "POC HEMATOCRIT": "Hematocrit [Volume Fraction] of Blood by Impedance",
    "POC Hematocrit": "Hematocrit [Volume Fraction] of Blood by Impedance",
    "POC Ketone Urine": "Ketones Test strip Ql (U)",
    "POC TRIGLYCERIDE": "Triglyceride [Mass/volume] in Blood",
    "POC Triglyceride": "Triglyceride [Mass/volume] in Blood",
    "POC Urine Ketones": "Ketones Test strip Ql (U)",
    "POC chloride": "Chloride [Moles/volume] in Blood",
    "POC co2": "CO2 (Bld) [Moles/Vol]",
    "POC creatinine": "Creatinine [Mass/volume] in Blood",
    "POC hct": "Hct VFr Bld Imped",
    "POC triglyceride": "Triglyceride [Mass/volume] in Blood",
    "POCT Glucose": "Glucose [Mass/Volume] in Blood",
    "POTASSIUM": "Potassium [Moles/Vol]",
    "POTASSIUM.": "Potassium [Moles/Vol]",
    "PR Interval": "P-R Interval",
    "PR interval": "P-R Interval",
    "PRO-TIME": "Prothrombin time (PT)",
    "PROCALCITONIN": "Procalcitonin [Mass/Vol]",
    "PRODUCT BLOOD TYPE": "Blood product type",
    "PROMYELOCYTE": "Promyelocytes [#/volume] in Blood by Manual count",
    "PROMYELOCYTES": "Promyelocytes [#/volume] in Blood by Manual count",
    "PROTEIN": "Prot SerPl-mCnc",
    "PROTEIN TOTAL": "Protein [Mass/Vol]",
    "PROTIME": "Prothrombin time (PT)",
    "PT ORDER": "Coagulation PT (PPP) [Time]",
    "PT Order": "Coagulation PT (PPP) [Time]",
    "PT PTT": "Prothrombin time (PT)",
    "PT/PTT": "Prothrombin time (PT)",
    "PTT": "Prothrombin time (PT)",
    "Performing Location": "Performing laboratory name",
    "Phosphorus, serum": "Phosphate [Mass/volume] in Serum or Plasma",
    "Plasma BUN": "Urea nitrogen [Mass/volume] in Serum or Plasma",
    "Plasma Calcium": "Calcium [Mass/volume] in Serum or Plasma",
    "Plasma Chloride": "Chloride [Moles/volume] in Serum or Plasma",
    "Plasma Chloride measurement": "Chloride [Moles/volume] in Serum or Plasma",
    "Plasma blood urea nitrogen": "Urea nitrogen [Mass/volume] in Serum or Plasma",
    "Plasma blood urea nitrogen measurement": "Urea nitrogen [Mass/volume] in Serum or Plasma",
    "Plasma magnesium measurement": "Magnesium [Mass/volume] in Serum or Plasma",
    "Platelet": "Platelets [#/volume] in Blood by Automated count",
    "Platelet Count": "Platelets [#/volume] in Blood by Automated count",
    "Platelet count": "Platelets [#/volume] in Blood by Automated count",
    "Platelets": "Platelets [#/volume] in Blood by Automated count",
    "Plt Morph": "Platelets [Morphology] in Blood",
    "Potassium": "Potassium [Moles/Vol]",
    "Procalcitonin": "Procalcitonin [Mass/Vol]",
    "Product Blood Type": "Blood product type",
    "Promyelocyte": "Promyelocytes [#/volume] in Blood by Manual count",
    "Promyelocytes": "Promyelocytes [#/volume] in Blood by Manual count",
    "Protein": "Prot SerPl-mCnc",
    "Protime": "Prothrombin time (PT)",
    "Q-T  INTERVAL": "Q-T interval",
    "Q-T INTERVAL": "Q-T interval",
    "Q-T Interval": "Q-T interval",
    "Q-T interval": "Q-T interval",
    "QRS AXIS": "QRS axis",
    "QRS DURATION": "QRS duration",
    "QRS Duration": "QRS duration",
    "QRS duration": "QRS duration",
    "QRSD INTERVAL": "QRS duration",
    "QRSD Interval": "QRS duration",
    "QRSD interval": "QRS duration",
    "QRSd Interval": "QRS duration",
    "QT INTERVAL": "Q-T interval",
    "QT Interval": "Q-T interval",
    "QT interval": "Q-T interval",
    "QT-Interval": "Q-T interval",
    "QTC INTERVAL": "Q-T interval corrected",
    "QTC Interval": "Q-T interval corrected",
    "QTC interval": "Q-T interval corrected",
    "QTc Interval": "Q-T interval corrected",
    "R AXIS": "R wave axis",
    "R Axis": "R wave axis",
    "R axis": "R wave axis",
    "R-Axis": "R wave axis",
    "RBC": "RBC # Bld Auto",
    "RBC MORPH": "RBC morph Bld",
    "RBC MORPH*": "RBC morph Bld",
    "RBC Morph": "RBC morph Bld",
    "RBC SMEAR": "RBC morphology finding Nom (Bld)",
    "RBC morph": "RBC morph Bld",
    "RBC's": "RBC # Bld Auto",
    "RBC.": "RBC # Bld Auto",
    "RBCMORPH": "RBC morph Bld",
    "RBCS": "RBC # Bld Auto",
    "RBCs": "RBC # Bld Auto",
    "RDW": "Erythrocyte DistWidth Bld Auto",
    "RDW CV": "Erythrocyte Auto (Bld) [DistWidth]",
    "RDW SD": "RDW RBC Auto",
    "RDW-CV": "Erythrocyte Auto (Bld) [DistWidth]",
    "RDW-CV, %": "Erythrocyte Auto (Bld) [DistWidth]",
    "RDW-CV,%": "Erythrocyte Auto (Bld) [DistWidth]",
    "RDW-SD": "RDW RBC Auto",
    "RDW-sd": "RDW RBC Auto",
    "RDW.": "Erythrocyte DistWidth Bld Auto",
    "RDWCV": "Erythrocyte Auto (Bld) [DistWidth]",
    "RDWS": "Erythrocyte DistWidth Bld Auto",
    "RDWSD": "RDW RBC Auto",
    "RDW_CVV": "Erythrocyte Auto (Bld) [DistWidth]",
    "RED BLOOD CELL COUNT": "Erythrocytes [#/volume] in Blood by Automated count",
    "RED BLOOD COUNT": "Erythrocytes [#/volume] in Blood by Automated count",
    "RENAL EPI": "Renal Epi Cells UrnS Ql Micro",
    "REP/VERIFIED": "Verified patient position",
    "RPR": "Reagin Ab [Presence] in Serum by RPR",
    "RPR (*)": "Reagin Ab [Presence] in Serum by RPR",
    "Rbc": "RBC # Bld Auto",
    "Rbc Morph": "RBC morph Bld",
    "RdW": "Erythrocyte DistWidth Bld Auto",
    "RdW-CV": "Erythrocyte Auto (Bld) [DistWidth]",
    "RdW-SD": "RDW RBC Auto",
    "Red Blood Cell Count": "Erythrocytes [#/volume] in Blood by Automated count",
    "Red Cell DistributionWidth": "Erythrocyte [DistWidth] in Blood by Automated count",
    "Red blood cell count": "Erythrocytes [#/volume] in Blood by Automated count",
    "Regular Diet": "Diet [Type]",
    "Renal EPI": "Renal Epi Cells UrnS Ql Micro",
    "Respiratory culture w Gram stain": "Microscopic observation [Identifier] in Bronchial specimen by Gram stain",
    "SGOT (AST)": "AST SerPl-cCnc",
    "SGOT(AST)": "AST SerPl-cCnc",
    "SGOT-AST": "AST SerPl-cCnc",
    "SGOT/AST": "AST SerPl-cCnc",
    "SGOT/AST.": "AST SerPl-cCnc",
    "SGPT (ALT)": "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "SGPT(ALT)": "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "SGPT-ALT": "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "SGPT/ALT": "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    "SLIDE REVIEW": "Pathologist review of Blood tests",
    "SODIUM": "Sodium [Moles/Vol]",
    "SODIUM.": "Sodium [Moles/Vol]",
    "SPEC GRAVITY": "Specific gravity of Urine",
    "SPEC SOURCE": "Specimen source identified",
    "SPECIFIC GRAVITY": "Specific gravity of Urine",
    "SPUTUM CULTURE": "Bacteria identified in Sputum by Respiratory culture",
    "SPUTUM CULTURE?": "Bacteria identified in Sputum by Respiratory culture",
    "SQUAMOUS EPI": "Epithelial cells.squamous LM Ql (Urine sed)",
    "Screen, Methadone": "Methadone Screen Ql (U)",
    "Serum anion gap measurement": "Anion gap in Serum or Plasma by calculation",
    "Slide Review": "Pathologist review of Blood tests",
    "Sodium": "Sodium [Moles/Vol]",
    "Spec Gravity": "Specific gravity of Urine",
    "Spec Source": "Specimen source identified",
    "Spec.Gravity": "Specific gravity of Urine",
    "Specific Gravity": "Specific gravity of Urine",
    "Sputum Culture": "Bacteria identified in Sputum by Respiratory culture",
    "Sputum culture": "Bacteria identified in Sputum by Respiratory culture",
    "Squamous EPI": "Epithelial cells.squamous LM Ql (Urine sed)",
    "Squamous epi": "Epithelial cells.squamous LM Ql (Urine sed)",
    "T AXIS": "T wave axis",
    "T Axis": "T wave axis",
    "T WAVE AXIS": "T wave axis",
    "T Wave Axis": "T wave axis",
    "T axis": "T wave axis",
    "T wave Axis": "T wave axis",
    "T wave axis": "T wave axis",
    "T-Axis": "T wave axis",
    "T-Wave Axis": "T wave axis",
    "T.I.B.C": "TIBC SerPl-mCnc",
    "THC": "Cannabinoids Ur Ql Scn",
    "TIBC": "TIBC SerPl-mCnc",
    "TOTAL BILI": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "TOTAL BILI.": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "TOTAL BILIRUBIN": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "TOTAL PROTEIN": "Protein [Mass/Vol]",
    "TOTAL PROTEIN.": "Protein [Mass/Vol]",
    "TP": "Protein [Mass/Vol]",
    "TRANS EPI": "Transitional cells [#/area] in Urine sediment by Microscopy high power field",
    "TRIG": "Trigl SerPl-mCnc",
    "TRIGLYCERIDE": "Triglyceride [Mass/Vol]",
    "TRIGLYCERIDES": "Triglyceride [Mass/Vol]",
    "TRIGLYCERIDES.": "Triglyceride [Mass/Vol]",
    "TROPONIN I": "Troponin I SerPl-mCnc",
    "TROPONIN-I": "Troponin I SerPl-mCnc",
    "TSH": "TSH Qn",
    "TSH-": "TSH Qn",
    "TSH.": "TSH Qn",
    "Total Bili": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "Total Bilirubin": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "Total Protein": "Protein [Mass/Vol]",
    "Total protein": "Protein [Mass/Vol]",
    "Trans EPI": "Transitional cells [#/area] in Urine sediment by Microscopy high power field",
    "Trans. Epi.": "Transitional cells [#/area] in Urine sediment by Microscopy high power field",
    "Trichomonas vaginalis nucleic acid detection by transcription mediated amplification": "Trichomonas vaginalis rRNA [Presence] in Specimen by NAA with probe detection",
    "Triglyceride": "Triglyceride [Mass/Vol]",
    "Triglycerides": "Triglyceride [Mass/Vol]",
    "Troponin I": "Troponin I SerPl-mCnc",
    "UNIT ABO": "ABO group [Type] in Blood from Blood product unit",
    "UNIT BLOOD TYPE": "Bld Prod Typ BPU",
    "URIC ACID": "Urate [Mass/Vol]",
    "URICACID": "Urate [Mass/Vol]",
    "URINALYSIS": "Urinalysis complete panel - Urine",
    "URINE CLARITY": "Clarity of Urine",
    "URINE COLOR": "Color of Urine",
    "URINE CREATININE": "Creatinine [Mass/volume] in Urine",
    "URINE CULTURE": "Bacteria identified in Urine by Culture",
    "URINE CULTURE, ROUTINE": "Bacteria identified in Urine by Culture",
    "URINE CULTURE?": "Bacteria identified in Urine by Culture",
    "URINE PH": "pH of Urine",
    "URINE SPECIFIC GRAVITY": "Specific gravity of Urine",
    "UROBILINOGEN": "Urobilinogen Ur-mCnc",
    "URobilinogen": "Urobilinogen Ur-mCnc",
    "Unit ABO": "ABO group [Type] in Blood from Blood product unit",
    "Unit Blood Type": "Bld Prod Typ BPU",
    "Uric Acid": "Urate [Mass/Vol]",
    "Urine Color": "Color of Urine",
    "Urine Creatinine": "Creatinine [Mass/volume] in Urine",
    "Urine Culture": "Bacteria identified in Urine by Culture",
    "Urine Ketones": "Ketones [Mass/volume] in Urine",
    "Urine Specific Gravity": "Specific gravity of Urine",
    "Urine culture": "Bacteria identified in Urine by Culture",
    "Urine culture routine": "Bacteria identified in Urine by Culture",
    "Urine pH": "pH of Urine",
    "Urobilinogen": "Urobilinogen Ur-mCnc",
    "Urobilinogens": "Urobilinogen Ur-mCnc",
    "User Id": "User ID.hospital assigned Abstractor",
    "V LDL": "Cholesterol in VLDL [Mass/Vol]",
    "VAR LYMPH": "Variant lymphocytes [#/volume] in Blood by Manual count",
    "VAR LYMPHS": "Variant lymphocytes [#/volume] in Blood by Manual count",
    "VENTRICULAR RATE": "Heart rate",
    "VITAMIN B 12": "Cobalamin (Vitamin B12) [Mass/Vol]",
    "VITAMIN B-12": "Cobalamin (Vitamin B12) [Mass/Vol]",
    "VITAMIN B12": "Cobalamin (Vitamin B12) [Mass/Vol]",
    "VITAMIN B12.": "Cobalamin (Vitamin B12) [Mass/Vol]",
    "VLDL": "Cholesterol in VLDL [Mass/Vol]",
    "VLDL.": "Cholesterol in VLDL [Mass/Vol]",
    "Venous blood oxygen saturation measurement": "Oxygen saturation in Venous blood",
    "Ventricular Rate": "Heart rate",
    "Ventricular rate": "Heart rate",
    "Vitamin B 12": "Cobalamin (Vitamin B12) [Mass/Vol]",
    "Vitamin B12": "Cobalamin (Vitamin B12) [Mass/Vol]",
    "WBC": "WBC # Bld Auto",
    "WBC corrected for nucleated RBC": "WBC corrected for nucl RBC Auto (Bld) [#/Vol]",
    "WBC'S": "WBC # Bld Auto",
    "WBC's": "WBC # Bld Auto",
    "WBC.": "WBC # Bld Auto",
    "WBCS": "WBC # Bld Auto",
    "WBCs": "WBC # Bld Auto",
    "WHITE BLOOD COUNT": "Leukocytes [#/volume] in Blood by Automated count",
    "Wbc": "WBC # Bld Auto",
    "Whole Blood Glucose": "Glucose [Mass/Volume] in Blood",
    "XR CHEST SINGLE VIEW": "XR Chest Single view",
    "_MPV": "PMV Bld Auto",
    "aPTT": "aPTT in Platelet poor plasma by Coagulation assay",
    "absolute basophil": "Basophils [#/volume] in Blood by Automated count",
    "absolute basophils": "Basophils [#/volume] in Blood by Automated count",
    "absolute eosinophil": "Eosinophils [#/volume] in Blood",
    "absolute eosinophils": "Eosinophils [#/volume] in Blood",
    "absolute immature granulocytes": "Immature granulocytes [#/volume] in Blood",
    "absolute lymphocytes": "Lymphocytes [#/volume] in Blood by Automated count",
    "absolute monocyte": "Monocytes [#/volume] in Blood by Automated count",
    "absolute monocytes": "Monocytes [#/volume] in Blood by Automated count",
    "absolute neutrophil": "Neutrophils [#/volume] in Blood by Automated count",
    "absolute neutrophils": "Neutrophils [#/volume] in Blood by Automated count",
    "additional comments": "General comment",
    "agap": "Anion gap in Serum or Plasma by calculation",
    "age": "Age",
    "alb": "Albumin [Mass/volume] in Serum or Plasma",
    "albumin": "Albumin [Mass/Vol]",
    "albumin globulin ratio": "Albumin/Globulin [Mass ratio]",
    "albumin serum": "Albumin [Mass/volume] in Serum or Plasma",
    "albumin, serum": "Albumin [Mass/volume] in Serum or Plasma",
    "albumin/globulin ratioo": "Albumin/Globulin [Mass ratio]",
    "alk phos": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "alkaline phos": "ALP [Catalytic activity/Vol]",
    "alkaline phosphatase": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "alkphos": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    "altsgpt": "ALT SerPl-cCnc",
    "altv": "ALT [Catalytic activity/Vol]",
    "amphetamine": "Amphetamine Screen Ql (U)",
    "amphetamines": "Amphetamines Ur Ql",
    "aniso": "Anisocytosis Bld Ql Smear",
    "appearance": "Appearance (U)",
    "ba#": "Basophils # Bld Auto",
    "bacteria": "Bacteria Bld Cult",
    "band": "Neuts Band NFr Bld Manual",
    "bands": "Neuts Band NFr Bld Manual",
    "baso": "Basophils # Bld Auto",
    "baso #": "Basophils # Bld Auto",
    "baso %": "Basophils NFr Bld Auto",
    "baso#": "Basophils # Bld Auto",
    "baso%": "Basophils NFr Bld Auto",
    "basophil": "Basophils [#/volume] in Blood by Automated count",
    "basophils": "Basophils [#/volume] in Blood by Automated count",
    "basos": "Basophils # Bld Auto",
    "benzo": "Benzodiaz Ur Ql",
    "benzodiazepine": "Benzodiazepines Ql (U)",
    "benzodiazepines": "Benzodiazepines Ql (U)",
    "benzodiazepines, urine screen": "Benzodiazepines [Presence] in Urine by Screen method",
    "bilirubin": "Bilirub SerPl-mCnc",
    "bilirubin - total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "bilirubin total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "bilirubin, total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "bilirubin,total": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "bilirubintotal": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "blast": "Blasts (Bld) [#/Vol]",
    "blood culture": "Bacteria identified in Blood by Culture",
    "blood urea nitrogen": "Urea nitrogen [Mass/volume] in Blood",
    "buncrea": "Urea nitrogen/Creatinine [Mass Ratio] in Serum or Plasma",
    "buprenorphine": "Buprenorphine Ur Ql",
    "cL": "Chloride SerPl-sCnc",
    "cL-": "Chloride SerPl-sCnc",
    "calcium": "Calcium [Mass/Vol]",
    "chloride": "Chloride [Moles/Vol]",
    "chlorides": "Chloride [Moles/Vol]",
    "chol HDL ratio": "Cholesterol.total/Cholesterol in HDL [Mass Ratio] in Serum or Plasma",
    "chol/HDL ratio": "Cholesterol.total/Cholesterol in HDL [Mass Ratio] in Serum or Plasma",
    "cholesterol": "Cholesterol [Mass/Vol]",
    "clarity": "Clarity (U)",
    "cocaine": "Benzoylecgonine Ql (U)",
    "cocaine metabolite": "Benzoylecgonine [Presence] in Urine",
    "color": "Color (U)",
    "comment": "Service comment",
    "comment(s)": "Service comment",
    "comments": "Service comment",
    "corrected calcium": "Calcium corrected for albumin [Mass/Vol]",
    "creat": "Creat SerPl-mCnc",
    "creat, plasma": "Creatinine [Mass/volume] in Serum or Plasma",
    "creatinine": "Creatinine [Mass/Vol]",
    "creatinine,S": "Creatinine [Mass/Vol]",
    "culture,urine": "Bacteria identified in Urine by Culture",
    "diagnosis": "Diagnosis",
    "e GFR": "eGFRcr SerPlBld CKD-EPI 2021",
    "e-GFR": "eGFRcr SerPlBld CKD-EPI 2021",
    "eGFR": "eGFRcr SerPlBld CKD-EPI 2021",
    "eGFR - AA": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "eGFR AA": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "eGFR S": "eGFRcr SerPlBld CKD-EPI 2021",
    "eGFR aa": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "eGFR*": "eGFRcr SerPlBld CKD-EPI 2021",
    "eGFR-aa": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "eGFR.": "eGFRcr SerPlBld CKD-EPI 2021",
    "eGFR.*": "eGFRcr SerPlBld CKD-EPI 2021",
    "eGFR..": "eGFRcr SerPlBld CKD-EPI 2021",
    "eGFRa": "Glomerular filtration rate [Volume Rate/Area] in Serum or Plasma by Creatinine-based formula (MDRD)/1.73 sq M",
    "eGFRaAA": "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (MDRD)/1.73 sq M among black population",
    "egfr": "eGFRcr SerPlBld CKD-EPI 2021",
    "egfra": "Glomerular filtration rate [Volume Rate/Area] in Serum or Plasma by Creatinine-based formula (MDRD)/1.73 sq M",
    "egfraa": "GFR Creatinine-based formula (MDRD)/1.73 sq M among black population (S/P/Bld) [Vol rate/Area]",
    "eo": "Eosinophils [#/volume] in Blood by Automated count",
    "eo #": "Eosinophil # Bld Auto",
    "eo %": "Eosinophil NFr Bld Auto",
    "eo#": "Eosinophil # Bld Auto",
    "eo#.": "Eosinophil # Bld Auto",
    "eo%": "Eosinophil NFr Bld Auto",
    "eos": "Eosinophils [#/volume] in Blood by Automated count",
    "eos %": "Eosinophil NFr Bld Auto",
    "eos%": "Eosinophil NFr Bld Auto",
    "eos.": "Eosinophils [#/volume] in Blood by Automated count",
    "eosinophil": "Eosinophils [#/volume] in Blood by Automated count",
    "eosinophils": "Eosinophils [#/volume] in Blood by Automated count",
    "epithelial": "Epithelial cells [Presence] in Urine sediment by Light microscopy",
    "fIO2": "FIO2",
    "fasting?": "Fasting status - Reported",
    "fentanyl": "fentaNYL Ur Ql",
    "fentanyl scrn (urine)": "fentaNYL [Presence] in Urine by Screen method",
    "fentanyl urine": "fentaNYL [Presence] in Urine",
    "fentanyl, qualitative, urine": "fentaNYL Ur Ql",
    "fentanyl, screen, urine": "fentaNYL [Presence] in Urine by Screen method",
    "fentanyl, urine, qualitative": "fentaNYL Ur Ql",
    "ferritin": "Ferritin [Mass/volume] in Serum or Plasma",
    "folate": "Folate [Mass/Vol]",
    "gfr": "eGFRcr SerPlBld CKD-EPI 2021",
    "globulin": "Globulin Calc (S) [Mass/Vol]",
    "glu": "Glucose [Mass/Vol]",
    "glucose": "Glucose [Mass/Vol]",
    "glucose POC": "Glucose (Bld) [Mass/Vol]",
    "glucose, cap": "Glucose [Mass/volume] in Capillary blood",
    "hCG, Urine": "HCG Ur Ql",
    "hcg urine": "HCG Ur Ql",
    "hdl": "Cholesterol in HDL [Mass/Vol]",
    "hematocrit": "Hematocrit Auto (Bld) [Volume fraction]",
    "hematocrit POC": "Hematocrit [Volume Fraction] of Blood by Impedance",
    "hemoglobin": "Hemoglobin [Mass/volume] in Blood",
    "hemoglobin S": "Hemoglobin S Solubility test Ql (Bld)",
    "hep b surf ag screen": "HBV surface Ag Confirm Ql",
    "hep b surf antigen scrn": "HBV surface Ag Confirm Ql",
    "hepatitis B surface antigen": "Hepatitis B virus surface Ag [Presence] in Serum or Plasma by Immunoassay",
    "hepatitis C antibody": "Hepatitis C virus Ab [Presence] in Serum",
    "hepatitis C antibody.": "Hepatitis C virus Ab [Presence] in Serum",
    "hgb s": "Hgb S Bld Ql Soly",
    "hyaline cast": "Hyaline casts [#/area] in Urine sediment by Microscopy low power field",
    "hyaline casts": "Hyaline casts [#/area] in Urine sediment by Microscopy low power field",
    "hydrocodone in urine": "HYDROcodone [Mass/volume] in Urine",
    "hydromorphone urine": "HYDROmorphone [Mass/volume] in Urine",
    "immature granulocyte": "Immature granulocytes [Presence] in Blood by Automated count",
    "immature granulocytes": "Immature granulocytes [Presence] in Blood by Automated count",
    "iron": "Iron [Mass/volume] in Serum or Plasma",
    "lactic acid": "Lactate [Moles/Vol]",
    "ldlhdl": "LDLc/HDLc SerPl",
    "leuk est": "Leukocytes [#/volume] in Blood by Estimate",
    "leukocyte": "Leukocytes [#/volume] in Blood by Automated count",
    "leukocyte esterase": "Leukocyte esterase [Presence] in Urine by Test strip",
    "leukocytes": "Leukocytes [#/volume] in Blood by Automated count",
    "lipase": "Lipase [Catalytic activity/Vol]",
    "ly %": "Lymphocytes NFr Bld Auto",
    "ly%": "Lymphocytes NFr Bld Auto",
    "lymph": "Lymphocytes [#/volume] in Blood by Automated count",
    "lymph #": "Lymphocytes # Bld Auto",
    "lymph %": "Lymphocytes NFr Bld Auto",
    "lymph#": "Lymphocytes # Bld Auto",
    "lymph%": "Lymphocytes NFr Bld Auto",
    "lymphocyte": "Lymphocytes [#/volume] in Blood by Automated count",
    "lymphocyte %": "Lymphocytes/Leukocytes in Blood by Automated count",
    "lymphocytes %": "Lymphocytes/Leukocytes in Blood by Automated count",
    "lymphs": "Lymphocytes [#/volume] in Blood by Automated count",
    "magnesium": "Magnesium [Moles/Vol]",
    "manual diff": "Manual differential performed Bld Ql",
    "mean corpuscular HGB conc": "MCHC [Entitic Mass/volume] in Red Blood Cells by Automated count",
    "mean corpuscular hemoglobin": "MCH [Entitic mass] by Automated count",
    "mean corpuscular volume": "MCV [Entitic mean volume] in Red Blood Cells by Automated count",
    "mean platelet volume": "Platelet [Entitic mean volume] in Blood by Automated count",
    "metamyelocyte": "Metamyelocytes # Bld",
    "metamyelocytes": "Metamyelocytes # Bld",
    "methadone": "Methadone [Mass/volume] in Urine",
    "methadone (u)": "Methadone [Mass/volume] in Urine",
    "methadone (urine)": "Methadone [Mass/volume] in Urine",
    "methadone qualitative urine": "Methadone Screen Ql (U)",
    "methadone scn (U)": "Methadone Screen Ql (U)",
    "mono": "Monocytes [#/volume] in Blood by Automated count",
    "mono #": "Monocytes [#/volume] in Blood by Automated count",
    "mono %": "Monocytes NFr Bld Auto",
    "mono#": "Monocytes [#/volume] in Blood by Automated count",
    "mono%": "Monocytes NFr Bld Auto",
    "monocyte": "Monocytes [#/volume] in Blood by Automated count",
    "monocyte %": "Monocytes/Leukocytes in Blood by Automated count",
    "monocytes": "Monocytes [#/volume] in Blood by Automated count",
    "monocytes %": "Monocytes/Leukocytes in Blood by Automated count",
    "monocytes%": "Monocytes/Leukocytes in Blood by Automated count",
    "monos": "Monocytes [#/volume] in Blood by Automated count",
    "monos.": "Monocytes [#/volume] in Blood by Automated count",
    "mucous": "Mucous Threads UrnS Ql Micro ",
    "myelocyte": "Myelocytes # Bld Manual",
    "myelocytes": "Myelocytes # Bld Manual",
    "nRBC": "nRBC # Bld Auto",
    "nRBC#": "nRBC # Bld Auto",
    "nRBC%": "nRBC Bld Auto-Rto",
    "nRBC, %": "nRBC Bld Auto-Rto",
    "neut #": "Neutrophils # Bld Auto",
    "neut %": "Neutrophils/Leukocytes in Blood by Automated count",
    "neut#": "Neutrophils # Bld Auto",
    "neut%": "Neutrophils/Leukocytes in Blood by Automated count",
    "neutrophil": "Neutrophils [#/volume] in Blood by Automated count",
    "neutrophils": "Neutrophils [#/volume] in Blood by Automated count",
    "nitrite": "Nitrite Ur Ql Strip",
    "nitrites": "Nitrite Ur Ql Strip",
    "note": "Note",
    "opiate": "Opiates Ur Ql",
    "opiates": "Opiates Ur Ql",
    "osmolality": "Osmolality [Osmolality]",
    "oxycodone": "oxyCODONE Screen Ql (U)",
    "pcp": "PCP Ur Ql",
    "performing lab": "Performing lab name",
    "plasma calcium measurement": "Calcium [Mass/volume] in Serum or Plasma",
    "platelet": "Platelets [#/volume] in Blood by Automated count",
    "platelet count": "Platelets [#/volume] in Blood by Automated count",
    "platelets": "Platelets [#/volume] in Blood by Automated count",
    "plt": "Platelet # Bld Auto",
    "plt est": "Platelets [#/volume] in Blood by Estimate",
    "plt morph": "Platelets [Morphology] in Blood",
    "plt.": "Platelet # Bld Auto",
    "pltest": "Platelets [#/volume] in Blood by Estimate",
    "pltmorph": "Platelets [Morphology] in Blood",
    "plts": "Platelet # Bld Auto",
    "potassium": "Potassium [Moles/Vol]",
    "pro calcitonin": "Procalcitonin [Mass/Vol]",
    "pro time": "Prothrombin time (PT)",
    "promyelocyte": "Promyelocytes [#/volume] in Blood by Manual count",
    "protein": "Prot SerPl-mCnc",
    "protein total": "Protein [Mass/Vol]",
    "protein, total": "Protein [Mass/Vol]",
    "protime": "Prothrombin time (PT)",
    "qrs axis": "QRS axis",
    "rdw-cv": "Erythrocyte Auto (Bld) [DistWidth]",
    "rdw-cv%": "Erythrocyte Auto (Bld) [DistWidth]",
    "rdw-sd": "RDW RBC Auto",
    "rdwcv": "Erythrocyte Auto (Bld) [DistWidth]",
    "rdwsd": "RDW RBC Auto",
    "red blood cell count": "Erythrocytes [#/volume] in Blood by Automated count",
    "red blood count": "Erythrocytes [#/volume] in Blood by Automated count",
    "red cell distribution width": "Erythrocyte [DistWidth] in Blood by Automated count",
    "regular diet": "Diet [Type]",
    "serum creat": "Creatinine [Mass/volume] in Serum or Plasma",
    "slide review": "Pathologist review of Blood tests",
    "slide review?": "Pathologist review of Blood tests",
    "sodium": "Sodium [Moles/Vol]",
    "spec gravity": "Specific gravity of Urine",
    "specific gravity": "Specific gravity of Urine",
    "total  bilirubin": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "total bili": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "total bilirubin": "Bilirubin.total [Mass/volume] in Serum or Plasma",
    "total protein": "Protein [Mass/Vol]",
    "trig": "Trigl SerPl-mCnc",
    "triglyceride": "Triglyceride [Mass/Vol]",
    "triglycerides": "Triglyceride [Mass/Vol]",
    "troponin I": "Troponin I SerPl-mCnc",
    "uric acid": "Urate [Mass/Vol]",
    "urine clarity": "Clarity of Urine",
    "urine color": "Color of Urine",
    "urine creatinine": "Creatinine [Mass/volume] in Urine",
    "urine culture": "Bacteria identified in Urine by Culture",
    "urine culture, routine": "Bacteria identified in Urine by Culture",
    "urine pH": "pH of Urine",
    "urine specific gravity": "Specific gravity of Urine",
    "urobilinogen": "Urobilinogen Ur-mCnc",
    "vitamin B-12": "Cobalamin (Vitamin B12) [Mass/Vol]",
    "vitamin B12": "Cobalamin (Vitamin B12) [Mass/Vol]",
    "wbc": "WBC # Bld Auto",
    "white blood count": "Leukocytes [#/volume] in Blood by Automated count",
}
