name: type check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ty:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'

      - name: Run type checks
        run: |
          ty check --python=$(which python)
