name: unit tests check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'

      - name: Run unit tests
        shell: bash
        run: |
          pytest --cov=recordlinker tests/unit
          mv .coverage coverage-${{ matrix.database }}.dat

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.database }}
          path: coverage-${{ matrix.database }}.dat

  coverage:
    runs-on: ubuntu-latest
    needs: pytest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage_artifacts
          pattern: coverage-*
          merge-multiple: true

      - name: Combine coverage reports
        run: |
          pip install coverage
          cd coverage_artifacts
          coverage combine coverage-*.dat
          coverage xml -o combined_coverage.xml

      - name: Upload combined coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage_artifacts/combined_coverage.xml
          verbose: true
