name: "post merged pull to slack"

on:
    pull_request_target:
      branches: [main]
      types:
        - closed

jobs:
  slack-pr-merged:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}

    steps:
      - name: Send GitHub trigger payload to Slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: ":github-merged: Pull request merged by ${{ github.event.pull_request.user.login }}\n\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>",
            blocks:
              - type: "section",
                text:
                  type: "mrkdwn"
                  text: ":github-merged: Pull request merged by ${{ github.event.pull_request.user.login }}\n\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
